version: 0.2
env:
  variables:
    IS_SEARCH_ENGINE_NO_INDEX: true
    IS_SERVICE_WORKER_USED: true
    IS_APP_ICON_DEV_ENABLE: true
    SHOULD_LOAD_DEVELOPING_RESOURCE: true
    CAN_PLAY_DEVELOPING_ARMDOZER: true
    CAN_PLAY_DEVELOPING_PILOT: true
    CAN_PLAY_EPISODE_IN_DEVELOPMENT: true
  parameter-store:
    SERVICE: /GbraverBurst/dev/service
    STAGE: /GbraverBurst/dev/stage
    ASSETLINKS_JSON_URI: /GbraverBurst/dev/assetlinksJsonURI
    GOOGLE_MEASUREMENT_ID: /GbraverBurst/dev/googleMeasurementID
    S3_BUCKET: /GbraverBurst/dev/s3Bucket
    DISTRIBUTION_ID: /GbraverBurst/dev/distributionId
    OWN_ROOT_URL: /GbraverBurst/dev/ownRootUrl
    TWITTER_SITE: /GbraverBurst/dev/twitterSite
    HOW_TO_PLAY_URL: /GbraverBurst/dev/howToPlayUrl
    TERMS_OF_SERVICE_URL: /GbraverBurst/dev/termsOfServiceUrl
    PRIVACY_POLICY_URL: /GbraverBurst/dev/privacyPolicyUrl
    CONTACT_URL: /GbraverBurst/dev/contactURL
    IS_PERFORMANCE_STATS_VISIBLE: /GbraverBurst/dev/isPerformanceStatsVisible
    IS_API_SERVER_ENABLE: /GbraverBurst/dev/isAPIServerEnable
    AUTH0_DOMAIN: /GbraverBurst/dev/auth0Domain
    AUTH0_CLIENT_ID: /GbraverBurst/dev/auth0ClientId
    AUTH0_AUDIENCE: /GbraverBurst/dev/auth0Audience
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - . ./buildspec-env
      - ./deploy.bash "${S3_BUCKET}" "${DISTRIBUTION_ID}" "${ASSETLINKS_JSON_URI}"