version: 0.2
env:
  variables:
    IS_SEARCH_ENGINE_NO_INDEX: true
    IS_SERVICE_WORKER_USED: true
    IS_APP_ICON_DEV_ENABLE: true
    CAN_PLAY_DEVELOPING_ARMDOZER: true
    CAN_PLAY_DEVELOPING_PILOT: true
    CAN_PLAY_EPISODE_IN_DEVELOPMENT: true
  parameter-store:
    SERVICE: /GbraverBurst/dev/service
    STAGE: /GbraverBurst/dev/stage
    ASSETLINKS_JSON_URI: /GbraverBurst/dev/assetlinksJsonURI
    S3_BUCKET: /GbraverBurst/dev/s3Bucket
    DISTRIBUTION_ID: /GbraverBurst/dev/distributionId
    OWN_ROOT_URL: /GbraverBurst/dev/ownRootUrl
    TWITTER_SITE: /GbraverBurst/dev/twitterSite
    HOW_TO_PLAY_URL: /GbraverBurst/dev/howToPlayUrl
    CHARACTER_DESCRIPTION_URL: /GbraverBurst/dev/characterDescriptionUrl
    TERMS_OF_SERVICE_URL: /GbraverBurst/dev/termsOfServiceUrl
    PRIVACY_POLICY_URL: /GbraverBurst/dev/privacyPolicyUrl
    CONTACT_URL: /GbraverBurst/dev/contactURL
    IS_API_SERVER_ENABLE: /GbraverBurst/dev/isAPIServerEnable
    COGNITO_USER_POOL_ID: /GbraverBurst/dev/cognitoUserPoolId
    COGNITO_CLIENT_ID: /GbraverBurst/dev/cognitoClientId
    COGNITO_HOSTED_UI_DOMAIN: /GbraverBurst/dev/cognitoHostedUIDomain
phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - . ./buildspec-env
      - ./deploy.bash "${S3_BUCKET}" "${STAGE}" "${ASSETLINKS_JSON_URI}"
      - ./clear-cdn.bash "${DISTRIBUTION_ID}"
