version: 0.2
env:
  parameter-store:
    DISTRIBUTION_ID: /GbraverBurst/dev/distributionId
    CLOUD_FRONT_ORIGIN_NAME: /GbraverBurst/dev/cloudFrontOriginName
phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - ./clear-cdn.bash "${DISTRIBUTION_ID}" "${CLOUD_FRONT_ORIGIN_NAME}" "${STAGE}"
