version: 0.2
env:
  variables:
    IS_SEARCH_ENGINE_NO_INDEX: true
  parameter-store:
    SERVICE: /GbraverBurst/dev/service
    STAGE: /GbraverBurst/dev/stage
    S3_BUCKET: /GbraverBurst/dev/s3Bucket
phases:
  build:
    commands:
      - ./overwrite-config-json.bash
