version: 0.2
env:
  variables:
    IS_SEARCH_ENGINE_NO_INDEX: false
    IS_SERVICE_WORKER_USED: true
    APP_ICON_TYPE: "PROD"
    CAN_PLAY_DEVELOPING_ARMDOZER: false
    CAN_PLAY_DEVELOPING_PILOT: false
    CAN_PLAY_EPISODE_IN_DEVELOPMENT: false
    IS_TITLE_HELP_ICON_ENABLE: true
    NETWORK_MODE: "ONLINE"
  parameter-store:
    SERVICE: /GbraverBurst/prod/service
    STAGE: /GbraverBurst/prod/stage
    WS_API_DOMAIN_NAME: /GbraverBurst/prod/wsApiDomainName
    ASSETLINKS_JSON_URI: /GbraverBurst/prod/assetlinksJsonURI
    S3_BUCKET: /GbraverBurst/prod/s3Bucket
    DISTRIBUTION_ID: /GbraverBurst/prod/distributionId
    OWN_ROOT_URL: /GbraverBurst/prod/ownRootUrl
    TWITTER_SITE: /GbraverBurst/prod/twitterSite
    HOW_TO_PLAY_URL: /GbraverBurst/prod/howToPlayUrl
    CHARACTER_DESCRIPTION_URL: /GbraverBurst/prod/characterDescriptionUrl
    TERMS_OF_SERVICE_URL: /GbraverBurst/prod/termsOfServiceUrl
    PRIVACY_POLICY_URL: /GbraverBurst/prod/privacyPolicyUrl
    CONTACT_URL: /GbraverBurst/prod/contactURL
    COGNITO_USER_POOL_ID: /GbraverBurst/prod/cognitoUserPoolId
    COGNITO_CLIENT_ID: /GbraverBurst/prod/cognitoClientId
    COGNITO_HOSTED_UI_DOMAIN: /GbraverBurst/prod/cognitoHostedUIDomain
phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - export WEBSOCKET_API_URL="wss://${WS_API_DOMAIN_NAME}/${STAGE}"
      - ./deploy.bash "${S3_BUCKET}" "${STAGE}" "${WEBSOCKET_API_URL}"
      - ./clear-cdn.bash "${DISTRIBUTION_ID}"
