version: 0.2
env:
  variables:
    IS_SEARCH_ENGINE_NO_INDEX: true
  parameter-store:
    SERVICE: /GbraverBurst/prod/service
    STAGE: /GbraverBurst/prod/stage
phases:
  build:
    commands:
      - ./overwrite-config-json.bash
