version: 0.2
env:
  parameter-store:
    SERVICE: /GbraverBurst/dev/service
    STAGE: /GbraverBurst/dev/stage
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm ci
      - npm run type-check
      - npm run test
  build:
    commands:
      - STACK_NAME="${SERVICE}-${STAGE}"
      - . ./env-from-cfn
      - ./deploy.sh "${S3_BUCKET}" "${DISTRIBUTION_ID}"