version: 0.2
env:
  variables:
    IS_SEARCH_ENGINE_NO_INDEX: false
    IS_SERVICE_WORKER_USED: true
    IS_APP_ICON_DEV_ENABLE: false
  parameter-store:
    SERVICE: /GbraverBurst/prod/service
    STAGE: /GbraverBurst/prod/stage
    ASSETLINKS_JSON_URI: /GbraverBurst/prod/assetlinksJsonURI
    GOOGLE_MEASUREMENT_ID: /GbraverBurst/prod/googleMeasurementID
    S3_BUCKET: /GbraverBurst/prod/s3Bucket
    DISTRIBUTION_ID: /GbraverBurst/prod/distributionId
    OWN_ROOT_URL: /GbraverBurst/prod/ownRootUrl
    TWITTER_SITE: /GbraverBurst/prod/twitterSite
    HOW_TO_PLAY_URL: /GbraverBurst/prod/howToPlayUrl
    TERMS_OF_SERVICE_URL: /GbraverBurst/prod/termsOfServiceUrl
    PRIVACY_POLICY_URL: /GbraverBurst/prod/privacyPolicyUrl
    CONTACT_URL: /GbraverBurst/prod/contactURL
    IS_PERFORMANCE_STATS_VISIBLE: /GbraverBurst/prod/isPerformanceStatsVisible
    IS_API_SERVER_ENABLE: /GbraverBurst/prod/isAPIServerEnable
    AUTH0_DOMAIN: /GbraverBurst/prod/auth0Domain
    AUTH0_CLIENT_ID: /GbraverBurst/prod/auth0ClientId
    AUTH0_AUDIENCE: /GbraverBurst/prod/auth0Audience
    CAN_PLAY_TUTORIAL_IN_DEVELOPMENT: /GbraverBurst/prod/canPlayTutorialInDevelopment
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm ci
      - npm run type-check
      - npm run test
  build:
    commands:
      - . ./buildspec-env
      - ./deploy.sh "${S3_BUCKET}" "${DISTRIBUTION_ID}" "${ASSETLINKS_JSON_URI}"