/** エピソードIDを集めたもの */
export const EpisodeIDs = {
  BATTERY_SYSTEM: "BATTERY_SYSTEM",
  ZERO_DEFENSE: "ZERO_DEFENSE",
  BURST: "BURST",
  TWO_BRAVER: "TWO_BRAVER",
  Pilot01: "Pilot01",
  Pilot02: "Pilot02",
  NATIONAL_TOURNAMENT_REVENGE: "NATIONAL_TOURNAMENT_REVENGE",
};
