/** エピソードIDを集めたもの */
export const EpisodeIDs = {
  BATTERY_SYSTEM: "BATTERY_SYSTEM",
  ZERO_DEFENSE: "ZERO_DEFENSE",
  BURST: "BURST",
  TWO_BRAVER: "TWO_BRAVER",
  SURVIVE_SUPER_POWER: "SURVIVE_SUPER_POWER",
  PILOT_01: "PILOT_01",
  PILOT_02: "PILOT_02",
  QUEEN_OF_TRAGEDY: "QUEEN_OF_TRAGEDY",
  PRINCE_OF_FALLEN_SUN: "PRINCE_OF_FALLEN_SUN",
};
